In [76]:
import pickle
from sklearn.ensemble import RandomForestClassifier
import os
from sklearn.metrics import confusion_matrix, roc_curve, auc

In [11]:
# os.chdir("../2_modeling/")
exec(open("train_model.py").read())

Preprocessing Stem & Join (P): 3.347217082977295
Preprocessing No Stem (P): 2.828143358230591
Preprocessing No Stem & Punct (P): 3.0154898166656494
TFIDF: 0.11683869361877441
Topics: 0.37028050422668457
Metadata: 0.9819507598876953
Syntax: 30.048978090286255
Embeddings: 78.09168791770935


In [13]:
feature_matrix.shape

(1050, 459)

In [14]:
ambiance = pickle.load(open("../../4_models/rf_ambiance_700iterations_athreshold_100_1.pickle", "rb"))
price = pickle.load(open("../../4_models/rf_price_700iterations_athreshold_100_1.pickle", "rb"))
service = pickle.load(open("../../4_models/rf_service_700iterations_athreshold_100_1.pickle", "rb"))
food = pickle.load(open("../../4_models/rf_food_700iterations_athreshold_100_1.pickle", "rb"))

ambiance_i = pickle.load(open("../../4_models/rf_ambiance_700iterations_athreshold_100_1initial.pickle", "rb"))
price_i = pickle.load(open("../../4_models/rf_price_700iterations_athreshold_100_1initial.pickle", "rb"))
service_i = pickle.load(open("../../4_models/rf_service_700iterations_athreshold_100_1initial.pickle", "rb"))
food_i = pickle.load(open("../../4_models/rf_food_700iterations_athreshold_100_1initial.pickle", "rb"))

In [80]:
def test(target_string, clf, clf2):
    X_tmp, y_tmp, X_test, y_test = iterative_train_test_split(
        np.array(feature_matrix),
        np.array(target[[target_string]]),
        test_size=0.2,
        random_state=10191994)

    X_train, y_train, X_validation, y_validation = iterative_train_test_split(
        X_tmp,
        y_tmp,
        test_size=0.25, # 0.25 * 0.8 = 0.2
        random_state=10191994)
    
    print(clf.score(X_validation[:, 1:], y_validation))
    print(confusion_matrix(y_validation,
            clf.predict(X_validation[:, 1:])))
    fpr, tpr, _ = roc_curve(y_validation,
                    clf.predict_proba(X_validation[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)
    
    print(clf2.score(X_validation[:, 1:], y_validation))
    print(confusion_matrix(y_validation,
            clf2.predict(X_validation[:, 1:])))
    fpr, tpr, _ = roc_curve(y_validation,
                    clf2.predict_proba(X_validation[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)

    print(clf.score(X_test[:, 1:], y_test))
    print(confusion_matrix(y_test,
            clf.predict(X_test[:, 1:])))
    fpr, tpr, _ = roc_curve(y_test,
                    clf.predict_proba(X_test[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)
    
    print(clf2.score(X_test[:, 1:], y_test))
    print(confusion_matrix(y_test,
            clf2.predict(X_test[:, 1:])))
    fpr, tpr, _ = roc_curve(y_test,
                    clf2.predict_proba(X_test[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)
    
#     return X_validation
    
#     print(clf.score(X_validation[:, 1:], y_validation))
#     print(confusion_matrix(y_validation,
#             clf.predict(X_validation[:, 1:])))

In [81]:
test("food", food_i, food)

0.8761904761904762
[[ 11   8]
 [ 18 173]]
auc: 0.8963901901350234
0.9
[[ 15   4]
 [ 17 174]]
auc: 0.9341416368145494
0.8809523809523809
[[ 15   4]
 [ 21 170]]
auc: 0.9129236704326261
0.8571428571428571
[[ 16   3]
 [ 27 164]]
auc: 0.9217415265913476


In [82]:
test("service", service_i, service)

0.8428571428571429
[[ 65  11]
 [ 22 112]]
auc: 0.9200706991358995
0.8523809523809524
[[ 67   9]
 [ 22 112]]
auc: 0.9114296936370778
0.8714285714285714
[[ 63  13]
 [ 14 120]]
auc: 0.9385310290652003
0.8571428571428571
[[ 63  13]
 [ 17 117]]
auc: 0.9406912804399058


In [84]:
test("price", price_i, price)

0.8523809523809524
[[131  24]
 [  7  48]]
auc: 0.9113196480938417
0.8428571428571429
[[129  26]
 [  7  48]]
auc: 0.906158357771261
0.861904761904762
[[133  22]
 [  7  48]]
auc: 0.9417008797653958
0.8714285714285714
[[136  19]
 [  8  47]]
auc: 0.9454545454545455


In [85]:
test("ambiance", ambiance_i, ambiance)

0.7904761904761904
[[102  23]
 [ 21  64]]
auc: 0.8817882352941177
0.8238095238095238
[[102  23]
 [ 14  71]]
auc: 0.8839529411764706
0.7857142857142857
[[101  24]
 [ 21  64]]
auc: 0.8815058823529411
0.8
[[100  25]
 [ 17  68]]
auc: 0.8832


In [86]:
    X_tmp, y_tmp, X_test, y_test = iterative_train_test_split(
        np.array(feature_matrix),
        np.array(target[["food"]]),
        test_size=0.2,
        random_state=10191994)

    X_train, y_train, X_validation, y_validation = iterative_train_test_split(
        X_tmp,
        y_tmp,
        test_size=0.25, # 0.25 * 0.8 = 0.2
        random_state=10191994)

In [91]:
with open("../../0_data/5_train_validation_test/X_train.pickle", "wb") as f:
    pickle.dump(X_train, f)

In [92]:
X_train_test = pickle.load(open("../../0_data/5_train_validation_test/X_train.pickle", "rb"))

In [93]:
X_train == X_train_test

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])