In [37]:
import pickle
from sklearn.ensemble import RandomForestClassifier
import os
from sklearn.metrics import confusion_matrix, roc_curve, auc, precision_recall_fscore_support

In [7]:
os.chdir("1_feature_engineering")
exec(open("extract_review_features.py").read())

In [8]:
feature_matrix.shape

(1050, 459)

In [9]:
feature_names = feature_matrix.columns[1:]

In [14]:
ambiance = pickle.load(open("../../4_models/rf_ambiance_700iterations_athreshold_100_1.pickle", "rb"))
price = pickle.load(open("../../4_models/rf_price_700iterations_athreshold_100_1.pickle", "rb"))
service = pickle.load(open("../../4_models/rf_service_700iterations_athreshold_100_1.pickle", "rb"))
food = pickle.load(open("../../4_models/rf_food_700iterations_athreshold_100_1.pickle", "rb"))

ambiance_i = pickle.load(open("../../4_models/rf_ambiance_700iterations_athreshold_100_1initial.pickle", "rb"))
price_i = pickle.load(open("../../4_models/rf_price_700iterations_athreshold_100_1initial.pickle", "rb"))
service_i = pickle.load(open("../../4_models/rf_service_700iterations_athreshold_100_1initial.pickle", "rb"))
food_i = pickle.load(open("../../4_models/rf_food_700iterations_athreshold_100_1initial.pickle", "rb"))

In [80]:
def test(target_string, clf, clf2):
    X_tmp, y_tmp, X_test, y_test = iterative_train_test_split(
        np.array(feature_matrix),
        np.array(target[[target_string]]),
        test_size=0.2,
        random_state=10191994)

    X_train, y_train, X_validation, y_validation = iterative_train_test_split(
        X_tmp,
        y_tmp,
        test_size=0.25, # 0.25 * 0.8 = 0.2
        random_state=10191994)
    
    print(clf.score(X_validation[:, 1:], y_validation))
    print(confusion_matrix(y_validation,
            clf.predict(X_validation[:, 1:])))
    fpr, tpr, _ = roc_curve(y_validation,
                    clf.predict_proba(X_validation[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)
    
    print(clf2.score(X_validation[:, 1:], y_validation))
    print(confusion_matrix(y_validation,
            clf2.predict(X_validation[:, 1:])))
    fpr, tpr, _ = roc_curve(y_validation,
                    clf2.predict_proba(X_validation[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)

    print(clf.score(X_test[:, 1:], y_test))
    print(confusion_matrix(y_test,
            clf.predict(X_test[:, 1:])))
    fpr, tpr, _ = roc_curve(y_test,
                    clf.predict_proba(X_test[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)
    
    print(clf2.score(X_test[:, 1:], y_test))
    print(confusion_matrix(y_test,
            clf2.predict(X_test[:, 1:])))
    fpr, tpr, _ = roc_curve(y_test,
                    clf2.predict_proba(X_test[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)
    
#     return X_validation
    
#     print(clf.score(X_validation[:, 1:], y_validation))
#     print(confusion_matrix(y_validation,
#             clf.predict(X_validation[:, 1:])))

In [81]:
test("food", food_i, food)

0.8761904761904762
[[ 11   8]
 [ 18 173]]
auc: 0.8963901901350234
0.9
[[ 15   4]
 [ 17 174]]
auc: 0.9341416368145494
0.8809523809523809
[[ 15   4]
 [ 21 170]]
auc: 0.9129236704326261
0.8571428571428571
[[ 16   3]
 [ 27 164]]
auc: 0.9217415265913476


In [82]:
test("service", service_i, service)

0.8428571428571429
[[ 65  11]
 [ 22 112]]
auc: 0.9200706991358995
0.8523809523809524
[[ 67   9]
 [ 22 112]]
auc: 0.9114296936370778
0.8714285714285714
[[ 63  13]
 [ 14 120]]
auc: 0.9385310290652003
0.8571428571428571
[[ 63  13]
 [ 17 117]]
auc: 0.9406912804399058


In [84]:
test("price", price_i, price)

0.8523809523809524
[[131  24]
 [  7  48]]
auc: 0.9113196480938417
0.8428571428571429
[[129  26]
 [  7  48]]
auc: 0.906158357771261
0.861904761904762
[[133  22]
 [  7  48]]
auc: 0.9417008797653958
0.8714285714285714
[[136  19]
 [  8  47]]
auc: 0.9454545454545455


In [85]:
test("ambiance", ambiance_i, ambiance)

0.7904761904761904
[[102  23]
 [ 21  64]]
auc: 0.8817882352941177
0.8238095238095238
[[102  23]
 [ 14  71]]
auc: 0.8839529411764706
0.7857142857142857
[[101  24]
 [ 21  64]]
auc: 0.8815058823529411
0.8
[[100  25]
 [ 17  68]]
auc: 0.8832


In [86]:
    X_tmp, y_tmp, X_test, y_test = iterative_train_test_split(
        np.array(feature_matrix),
        np.array(target[["food"]]),
        test_size=0.2,
        random_state=10191994)

    X_train, y_train, X_validation, y_validation = iterative_train_test_split(
        X_tmp,
        y_tmp,
        test_size=0.25, # 0.25 * 0.8 = 0.2
        random_state=10191994)

In [91]:
with open("../../0_data/5_train_validation_test/X_train.pickle", "wb") as f:
    pickle.dump(X_train, f)

In [92]:
X_train_test = pickle.load(open("../../0_data/5_train_validation_test/X_train.pickle", "rb"))

In [93]:
X_train == X_train_test

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

#### New models with 1000 iterations sped up

In [50]:
ambiance = pickle.load(open("../../4_models/rf_ambiance_4iterations_athreshold_5000_200.pickle", "rb"))
price = pickle.load(open("../../4_models/rf_price_4iterations_athreshold_5000_200.pickle", "rb"))
service = pickle.load(open("../../4_models/rf_service_4iterations_athreshold_5000_200.pickle", "rb"))
food = pickle.load(open("../../4_models/rf_food_4iterations_athreshold_5000_200.pickle", "rb"))

ambiance_1050 = pickle.load(open("../../4_models/rf_ambiance_4iterations_athreshold_5000_200_1050.pickle", "rb"))
price_1050 = pickle.load(open("../../4_models/rf_price_4iterations_athreshold_5000_200_1050.pickle", "rb"))
service_1050 = pickle.load(open("../../4_models/rf_service_4iterations_athreshold_5000_200_1050.pickle", "rb"))
food_1050 = pickle.load(open("../../4_models/rf_food_4iterations_athreshold_5000_200_1050.pickle", "rb"))

ambiance_i = pickle.load(open("../../4_models/rf_ambiance_4iterations_athreshold_5000_200initial.pickle", "rb"))
price_i = pickle.load(open("../../4_models/rf_price_4iterations_athreshold_5000_200initial.pickle", "rb"))
service_i = pickle.load(open("../../4_models/rf_service_4iterations_athreshold_5000_200initial.pickle", "rb"))
food_i = pickle.load(open("../../4_models/rf_food_4iterations_athreshold_5000_200initial.pickle", "rb"))

In [51]:
def test2(clf, clf2, features, target):
    
    print(clf.score(features[:, 1:], target))
    print(confusion_matrix(target,
            clf.predict(features[:, 1:])))
    print(precision_recall_fscore_support(target,
            clf.predict(features[:, 1:])))
    fpr, tpr, _ = roc_curve(target,
                    clf.predict_proba(features[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)
    
    print(clf2.score(features[:, 1:], target))
    print(confusion_matrix(target,
            clf2.predict(features[:, 1:])))
    print(precision_recall_fscore_support(target,
            clf2.predict(features[:, 1:])))
    fpr, tpr, _ = roc_curve(target,
                    clf2.predict_proba(features[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)

In [58]:
X_train_ambiance = pickle.load(open("../../0_data/5_train_validation_test/X_train_ambiance_1050.pickle", "rb"))
y_train_ambiance = pickle.load(open("../../0_data/5_train_validation_test/X_train_ambiance_1050.pickle", "rb"))
X_validation_ambiance = pickle.load(open("../../0_data/5_train_validation_test/X_validation_ambiance_1050.pickle", "rb"))
y_validation_ambiance = pickle.load(open("../../0_data/5_train_validation_test/y_validation_ambiance_1050.pickle", "rb"))
X_test_ambiance = pickle.load(open("../../0_data/5_train_validation_test/X_test_ambiance_1050.pickle", "rb"))
y_test_ambiance = pickle.load(open("../../0_data/5_train_validation_test/y_test_ambiance_1050.pickle", "rb"))

In [59]:
print(ambiance_i.score(X_validation_ambiance[:,1:], y_validation_ambiance))
print(ambiance_i.score(X_test_ambiance[:,1:], y_test_ambiance))
print(ambiance_1050.score(X_validation_ambiance[:,1:], y_validation_ambiance))
print(ambiance_1050.score(X_test_ambiance[:,1:], y_test_ambiance))

0.7952380952380952
0.8142857142857143
0.8047619047619048
0.7904761904761904


In [60]:
test2(ambiance_i, ambiance_1050, X_validation_ambiance, y_validation_ambiance)
test2(ambiance_i, ambiance_1050, X_test_ambiance, y_test_ambiance)

0.7952380952380952
[[101  24]
 [ 19  66]]
(array([0.84166667, 0.73333333]), array([0.808     , 0.77647059]), array([0.8244898 , 0.75428571]), array([125,  85]))
auc: 0.9059764705882353
0.8047619047619048
[[106  19]
 [ 22  63]]
(array([0.828125  , 0.76829268]), array([0.848     , 0.74117647]), array([0.83794466, 0.75449102]), array([125,  85]))
auc: 0.8837647058823529
0.8142857142857143
[[100  25]
 [ 14  71]]
(array([0.87719298, 0.73958333]), array([0.8       , 0.83529412]), array([0.83682008, 0.78453039]), array([125,  85]))
auc: 0.8906352941176471
0.7904761904761904
[[106  19]
 [ 25  60]]
(array([0.80916031, 0.75949367]), array([0.848     , 0.70588235]), array([0.828125  , 0.73170732]), array([125,  85]))
auc: 0.8818823529411765


In [17]:
sorted(list(zip(feature_names, ambiance_i.feature_importances_)), key=lambda x: -x[1])

[('ambiance_3avg_similarity', 0.4558579486446677),
 ('patio_3avg_similarity', 0.2538761719992587),
 ('loud_3avg_similarity', 0.13852747194738405),
 ('topic_0', 0.02701418452551707),
 ('topic_8', 0.007329089163042121),
 ('topic_25', 0.007008817937162035),
 ('say', 0.0066878442119556),
 ('staff_3avg_sim', 0.006197194821548695),
 ('topic_30', 0.005869708140676059),
 ('service_3avg_sim', 0.00339727042399861),
 ('topic_22', 0.003247900260025838),
 ('topic_13', 0.0032361751689151375),
 ('topic_94', 0.0029957788771828925),
 ('topic_70', 0.0027088922008283766),
 ('food_3avg_sim', 0.0020995114527998936),
 ('ask', 0.0020636811294479245),
 ('NOUN_VERB', 0.0019543215329108476),
 ('topic_6', 0.001813823492936451),
 ('topic_84', 0.0015538830896689789),
 ('topic_68', 0.0014710507612989286),
 ('VERB', 0.0013889827190943956),
 ('topic_33', 0.00134796086013714),
 ('topic_85', 0.0012694350887545044),
 ('ADJ_VERB', 0.0012681018365810603),
 ('topic_48', 0.001258964580345355),
 ('topic_62', 0.00123686561935

In [18]:
sorted(list(zip(feature_names, ambiance.feature_importances_)), key=lambda x: -x[1])

[('ambiance_3avg_similarity', 0.5112938042919619),
 ('patio_3avg_similarity', 0.21658958909898526),
 ('loud_3avg_similarity', 0.14171349073485548),
 ('topic_0', 0.03429864658358091),
 ('say', 0.006215964171200039),
 ('topic_8', 0.005607139267710017),
 ('topic_30', 0.005464456032657118),
 ('topic_25', 0.004400704828973885),
 ('topic_70', 0.003748536130142973),
 ('topic_94', 0.002241032383458926),
 ('topic_13', 0.0022184690259822075),
 ('service_3avg_sim', 0.0021216119018462945),
 ('topic_55', 0.001995282036213574),
 ('topic_6', 0.0019070700465315398),
 ('VERB', 0.0018753330315295432),
 ('topic_22', 0.0016366192580038984),
 ('topic_50', 0.00154529161451765),
 ('ADJ_VERB', 0.001256026918575595),
 ('staff_3avg_sim', 0.0012488782960948473),
 ('topic_83', 0.0012131975788223625),
 ('topic_63', 0.0012116582746339003),
 ('food_3avg_sim', 0.0010994948738448857),
 ('topic_32', 0.0010349902351532722),
 ('ask', 0.0010192152811303093),
 ('server', 0.0009490787776398939),
 ('ADJ', 0.00088964125899010

In [19]:
X_train_price = pickle.load(open("../../0_data/5_train_validation_test/X_train_price_1050.pickle", "rb"))
y_train_price = pickle.load(open("../../0_data/5_train_validation_test/X_train_price_1050.pickle", "rb"))
X_validation_price = pickle.load(open("../../0_data/5_train_validation_test/X_validation_price_1050.pickle", "rb"))
y_validation_price = pickle.load(open("../../0_data/5_train_validation_test/y_validation_price_1050.pickle", "rb"))
X_test_price = pickle.load(open("../../0_data/5_train_validation_test/X_test_price_1050.pickle", "rb"))
y_test_price = pickle.load(open("../../0_data/5_train_validation_test/y_test_price_1050.pickle", "rb"))

In [20]:
print(price_i.score(X_validation_price[:,1:], y_validation_price))
print(price_i.score(X_test_price[:,1:], y_test_price))
print(price.score(X_validation_price[:,1:], y_validation_price))
print(price.score(X_test_price[:,1:], y_test_price))

0.8571428571428571
0.8428571428571429
0.8714285714285714
0.8428571428571429


In [21]:
test2(price_i, price, X_validation_price, y_validation_price)
test2(price_i, price, X_test_price, y_test_price)

0.8571428571428571
[[132  23]
 [  7  48]]
auc: 0.9070967741935484
0.8714285714285714
[[135  20]
 [  7  48]]
auc: 0.903108504398827
0.8428571428571429
[[128  27]
 [  6  49]]
auc: 0.9317302052785924
0.8428571428571429
[[132  23]
 [ 10  45]]
auc: 0.9311436950146628


In [22]:
sorted(list(zip(feature_names, price_i.feature_importances_)), key=lambda x: -x[1])

[('price_3avg_similarity', 0.49774685254048934),
 ('cost_3avg_similarity', 0.17518609029495555),
 ('price', 0.08162793858297336),
 ('sen_money_len', 0.04911415254500227),
 ('topic_94', 0.010537136437791864),
 ('sen_num_len', 0.010141017441871679),
 ('seat', 0.00998326783114876),
 ('topic_12', 0.009297601030588102),
 ('topic_13', 0.00868357724803577),
 ('topic_39', 0.005756593665359199),
 ('topic_72', 0.00496127431830757),
 ('topic_55', 0.00476931549592572),
 ('topic_18', 0.004655199628361845),
 ('topic_91', 0.004380629226409474),
 ('topic_8', 0.004080655413226548),
 ('topic_86', 0.00391485524194743),
 ('delicious_3avg_sim', 0.003877063517792804),
 ('topic_28', 0.003778866683561682),
 ('order', 0.003282130491822625),
 ('topic_71', 0.002959280935000968),
 ('delici', 0.0029571118111401777),
 ('topic_38', 0.0025259900467158097),
 ('topic_29', 0.002513386418197612),
 ('food_3avg_sim', 0.002454690295195755),
 ('topic_60', 0.002333507816562237),
 ('topic_63', 0.002222675862634378),
 ('topic_2

In [23]:
sorted(list(zip(feature_names, price.feature_importances_)), key=lambda x: -x[1])

[('price_3avg_similarity', 0.5479403207760278),
 ('cost_3avg_similarity', 0.10378696609706664),
 ('price', 0.08611801439960089),
 ('NUM_ADP', 0.03265819869946724),
 ('NUM_PRT', 0.03139660688512669),
 ('sen_money_len', 0.027994973042616784),
 ('topic_91', 0.008051357824162485),
 ('topic_34', 0.00788513341147698),
 ('sen_num_len', 0.006527138826434501),
 ('X_ADJ', 0.006125770152924423),
 ('topic_39', 0.006050038915157816),
 ('topic_18', 0.005779073293147526),
 ('VERB_X', 0.005093825401334527),
 ('seat', 0.00504720775893671),
 ('topic_12', 0.004839797925394966),
 ('topic_86', 0.004607811007684857),
 ('NUM_PRON', 0.004551218274999244),
 ('topic_13', 0.004533893135621944),
 ('X', 0.004495022321603816),
 ('._X', 0.003539239882823931),
 ('VERB', 0.0033280681237257592),
 ('topic_64', 0.003024789359295013),
 ('topic_63', 0.0028578384522775445),
 ('topic_28', 0.002753317639163307),
 ('delicious_3avg_sim', 0.0023771367254097424),
 ('topic_94', 0.0023282665630550104),
 ('topic_8', 0.00212135931960

In [25]:
X_train_service = pickle.load(open("../../0_data/5_train_validation_test/X_train_service_1050.pickle", "rb"))
y_train_service = pickle.load(open("../../0_data/5_train_validation_test/X_train_service_1050.pickle", "rb"))
X_validation_service = pickle.load(open("../../0_data/5_train_validation_test/X_validation_service_1050.pickle", "rb"))
y_validation_service = pickle.load(open("../../0_data/5_train_validation_test/y_validation_service_1050.pickle", "rb"))
X_test_service = pickle.load(open("../../0_data/5_train_validation_test/X_test_service_1050.pickle", "rb"))
y_test_service = pickle.load(open("../../0_data/5_train_validation_test/y_test_service_1050.pickle", "rb"))

In [26]:
print(service_i.score(X_validation_service[:,1:], y_validation_service))
print(service_i.score(X_test_service[:,1:], y_test_service))
print(service.score(X_validation_service[:,1:], y_validation_service))
print(service.score(X_test_service[:,1:], y_test_service))

0.8476190476190476
0.861904761904762
0.8571428571428571
0.861904761904762


In [27]:
test2(service_i, service, X_validation_service, y_validation_service)
test2(service_i, service, X_test_service, y_test_service)

0.8476190476190476
[[ 66  10]
 [ 22 112]]
auc: 0.9134917517674784
0.8571428571428571
[[ 66  10]
 [ 20 114]]
auc: 0.9128043990573449
0.861904761904762
[[ 61  15]
 [ 14 120]]
auc: 0.9350942655145327
0.861904761904762
[[ 61  15]
 [ 14 120]]
auc: 0.9339159465828751


In [28]:
sorted(list(zip(feature_names, service_i.feature_importances_)), key=lambda x: -x[1])

[('service_3avg_sim', 0.36249057570372234),
 ('staff_3avg_sim', 0.336076200654755),
 ('servic', 0.12562808426935065),
 ('topic_22', 0.033985550637444635),
 ('topic_16', 0.009133884016434226),
 ('price_3avg_similarity', 0.008599053933073348),
 ('topic_94', 0.007842416028975728),
 ('wait', 0.006492405242925114),
 ('topic_31', 0.005970244067977292),
 ('ambiance_3avg_similarity', 0.0038987933767863905),
 ('topic_72', 0.003770277495375978),
 ('eat', 0.0034106567104659658),
 ('topic_6', 0.003093542408915838),
 ('cost_3avg_similarity', 0.0029920111195465737),
 ('patio_3avg_similarity', 0.002911978139735099),
 ('food_3avg_sim', 0.0026279789458943034),
 ('place', 0.0026277670327164732),
 ('tast', 0.002395121704579586),
 ('topic_33', 0.0023308642935905887),
 ('topic_99', 0.0023095713561639207),
 ('topic_86', 0.0021997986279198405),
 ('topic_18', 0.0021526787959792303),
 ('topic_15', 0.0019388808256757628),
 ('day', 0.0018777536853679861),
 ('topic_48', 0.001797997326524379),
 ('delicious_3avg_si

In [29]:
sorted(list(zip(feature_names, service.feature_importances_)), key=lambda x: -x[1])

[('service_3avg_sim', 0.4136337672526222),
 ('staff_3avg_sim', 0.32030157836390755),
 ('servic', 0.10793243126957505),
 ('topic_22', 0.0299328506661783),
 ('topic_16', 0.009390128908460988),
 ('topic_94', 0.007196237016060788),
 ('price_3avg_similarity', 0.00659504599637997),
 ('wait', 0.005163686501067168),
 ('topic_31', 0.005091723327424614),
 ('ambiance_3avg_similarity', 0.004967193419004387),
 ('patio_3avg_similarity', 0.004334235306173467),
 ('topic_72', 0.0037409830932936803),
 ('topic_6', 0.0027736662139644565),
 ('cost_3avg_similarity', 0.0024691272612865447),
 ('topic_99', 0.0024587295480303943),
 ('eat', 0.0024343834314060173),
 ('topic_48', 0.002184568609116983),
 ('topic_18', 0.0021462529418062514),
 ('tast', 0.002111548839944088),
 ('topic_33', 0.0020176119669081576),
 ('place', 0.0018078060010410168),
 ('topic_15', 0.001711856637030073),
 ('topic_86', 0.0016584384031329666),
 ('back', 0.001500078610409179),
 ('topic_65', 0.001477502978766697),
 ('day', 0.00141906220135233

In [30]:
X_train_food = pickle.load(open("../../0_data/5_train_validation_test/X_train_food_1050.pickle", "rb"))
y_train_food = pickle.load(open("../../0_data/5_train_validation_test/X_train_food_1050.pickle", "rb"))
X_validation_food = pickle.load(open("../../0_data/5_train_validation_test/X_validation_food_1050.pickle", "rb"))
y_validation_food = pickle.load(open("../../0_data/5_train_validation_test/y_validation_food_1050.pickle", "rb"))
X_test_food = pickle.load(open("../../0_data/5_train_validation_test/X_test_food_1050.pickle", "rb"))
y_test_food = pickle.load(open("../../0_data/5_train_validation_test/y_test_food_1050.pickle", "rb"))

In [31]:
print(food_i.score(X_validation_food[:,1:], y_validation_food))
print(food_i.score(X_test_food[:,1:], y_test_food))
print(food.score(X_validation_food[:,1:], y_validation_food))
print(food.score(X_test_food[:,1:], y_test_food))

0.8857142857142857
0.861904761904762
0.9238095238095239
0.8857142857142857


In [32]:
test2(food_i, food, X_validation_food, y_validation_food)
test2(food_i, food, X_test_food, y_test_food)

0.8857142857142857
[[ 13   6]
 [ 18 173]]
auc: 0.8969413061449435
0.9238095238095239
[[ 13   6]
 [ 10 181]]
auc: 0.9104436483879857
0.861904761904762
[[ 11   8]
 [ 21 170]]
auc: 0.8820611738771011
0.8857142857142857
[[ 10   9]
 [ 15 176]]
auc: 0.8677321576191789


In [33]:
sorted(list(zip(feature_names, food_i.feature_importances_)), key=lambda x: -x[1])

[('delicious_3avg_sim', 0.34345440718431175),
 ('food_3avg_sim', 0.09523621775160265),
 ('topic_2', 0.09242838223974668),
 ('topic_70', 0.03501484031483067),
 ('topic_86', 0.024608367943941268),
 ('food', 0.021180645193952696),
 ('topic_29', 0.01706744534551686),
 ('room', 0.016113743457168497),
 ('topic_0', 0.014771552011423116),
 ('patio_3avg_similarity', 0.013679417483817607),
 ('made', 0.011733510668543445),
 ('much', 0.010948120281859307),
 ('loud_3avg_similarity', 0.010264972603246174),
 ('cost_3avg_similarity', 0.01003439487616529),
 ('topic_94', 0.009785909275690551),
 ('topic_39', 0.009785908650687975),
 ('peopl', 0.008640044767833614),
 ('topic_66', 0.008280506737380419),
 ('topic_55', 0.007631687016239634),
 ('topic_72', 0.00743834715808391),
 ('good', 0.007327390335608589),
 ('topic_44', 0.007323381943074513),
 ('bar', 0.006809838595645156),
 ('place', 0.006575062743718849),
 ('staff_3avg_sim', 0.006347823720507666),
 ('topic_87', 0.006153894651237535),
 ('topic_43', 0.0061

In [34]:
sorted(list(zip(feature_names, food.feature_importances_)), key=lambda x: -x[1])

[('delicious_3avg_sim', 0.4496144666390744),
 ('food_3avg_sim', 0.1359473072031455),
 ('topic_2', 0.048925178193506697),
 ('food', 0.019656930517427965),
 ('much', 0.016512206238693358),
 ('topic_70', 0.015934073351081927),
 ('room', 0.014170999331182293),
 ('topic_0', 0.013579931330680603),
 ('topic_86', 0.012221972637827221),
 ('ADV_PRON', 0.011840389703044902),
 ('place', 0.010841203832917305),
 ('PRON_ADV', 0.010339639448724179),
 ('patio_3avg_similarity', 0.009909401853844596),
 ('topic_29', 0.009431430123063899),
 ('topic_39', 0.0077175103562572255),
 ('VERB_PRON', 0.00743802410809012),
 ('topic_55', 0.007358676423875438),
 ('ADJ_PRT', 0.0072261026335360854),
 ('topic_44', 0.0065659508513625986),
 ('VERB_CONJ', 0.006116605114922767),
 ('topic_72', 0.00605721057726929),
 ('made', 0.005942322457722535),
 ('peopl', 0.005690540002159878),
 ('NUM_CONJ', 0.00552397357628242),
 ('topic_94', 0.005275357000545705),
 ('good', 0.004903915113560037),
 ('bar', 0.004898817540186494),
 ('loud_3