In [76]:
import pickle
from sklearn.ensemble import RandomForestClassifier
import os
from sklearn.metrics import confusion_matrix, roc_curve, auc

In [11]:
# os.chdir("../2_modeling/")
exec(open("train_model.py").read())

Preprocessing Stem & Join (P): 3.347217082977295
Preprocessing No Stem (P): 2.828143358230591
Preprocessing No Stem & Punct (P): 3.0154898166656494
TFIDF: 0.11683869361877441
Topics: 0.37028050422668457
Metadata: 0.9819507598876953
Syntax: 30.048978090286255
Embeddings: 78.09168791770935


In [13]:
feature_matrix.shape

(1050, 459)

In [114]:
feature_names = feature_matrix.columns[1:]

In [14]:
ambiance = pickle.load(open("../../4_models/rf_ambiance_700iterations_athreshold_100_1.pickle", "rb"))
price = pickle.load(open("../../4_models/rf_price_700iterations_athreshold_100_1.pickle", "rb"))
service = pickle.load(open("../../4_models/rf_service_700iterations_athreshold_100_1.pickle", "rb"))
food = pickle.load(open("../../4_models/rf_food_700iterations_athreshold_100_1.pickle", "rb"))

ambiance_i = pickle.load(open("../../4_models/rf_ambiance_700iterations_athreshold_100_1initial.pickle", "rb"))
price_i = pickle.load(open("../../4_models/rf_price_700iterations_athreshold_100_1initial.pickle", "rb"))
service_i = pickle.load(open("../../4_models/rf_service_700iterations_athreshold_100_1initial.pickle", "rb"))
food_i = pickle.load(open("../../4_models/rf_food_700iterations_athreshold_100_1initial.pickle", "rb"))

In [80]:
def test(target_string, clf, clf2):
    X_tmp, y_tmp, X_test, y_test = iterative_train_test_split(
        np.array(feature_matrix),
        np.array(target[[target_string]]),
        test_size=0.2,
        random_state=10191994)

    X_train, y_train, X_validation, y_validation = iterative_train_test_split(
        X_tmp,
        y_tmp,
        test_size=0.25, # 0.25 * 0.8 = 0.2
        random_state=10191994)
    
    print(clf.score(X_validation[:, 1:], y_validation))
    print(confusion_matrix(y_validation,
            clf.predict(X_validation[:, 1:])))
    fpr, tpr, _ = roc_curve(y_validation,
                    clf.predict_proba(X_validation[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)
    
    print(clf2.score(X_validation[:, 1:], y_validation))
    print(confusion_matrix(y_validation,
            clf2.predict(X_validation[:, 1:])))
    fpr, tpr, _ = roc_curve(y_validation,
                    clf2.predict_proba(X_validation[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)

    print(clf.score(X_test[:, 1:], y_test))
    print(confusion_matrix(y_test,
            clf.predict(X_test[:, 1:])))
    fpr, tpr, _ = roc_curve(y_test,
                    clf.predict_proba(X_test[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)
    
    print(clf2.score(X_test[:, 1:], y_test))
    print(confusion_matrix(y_test,
            clf2.predict(X_test[:, 1:])))
    fpr, tpr, _ = roc_curve(y_test,
                    clf2.predict_proba(X_test[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)
    
#     return X_validation
    
#     print(clf.score(X_validation[:, 1:], y_validation))
#     print(confusion_matrix(y_validation,
#             clf.predict(X_validation[:, 1:])))

In [81]:
test("food", food_i, food)

0.8761904761904762
[[ 11   8]
 [ 18 173]]
auc: 0.8963901901350234
0.9
[[ 15   4]
 [ 17 174]]
auc: 0.9341416368145494
0.8809523809523809
[[ 15   4]
 [ 21 170]]
auc: 0.9129236704326261
0.8571428571428571
[[ 16   3]
 [ 27 164]]
auc: 0.9217415265913476


In [82]:
test("service", service_i, service)

0.8428571428571429
[[ 65  11]
 [ 22 112]]
auc: 0.9200706991358995
0.8523809523809524
[[ 67   9]
 [ 22 112]]
auc: 0.9114296936370778
0.8714285714285714
[[ 63  13]
 [ 14 120]]
auc: 0.9385310290652003
0.8571428571428571
[[ 63  13]
 [ 17 117]]
auc: 0.9406912804399058


In [84]:
test("price", price_i, price)

0.8523809523809524
[[131  24]
 [  7  48]]
auc: 0.9113196480938417
0.8428571428571429
[[129  26]
 [  7  48]]
auc: 0.906158357771261
0.861904761904762
[[133  22]
 [  7  48]]
auc: 0.9417008797653958
0.8714285714285714
[[136  19]
 [  8  47]]
auc: 0.9454545454545455


In [85]:
test("ambiance", ambiance_i, ambiance)

0.7904761904761904
[[102  23]
 [ 21  64]]
auc: 0.8817882352941177
0.8238095238095238
[[102  23]
 [ 14  71]]
auc: 0.8839529411764706
0.7857142857142857
[[101  24]
 [ 21  64]]
auc: 0.8815058823529411
0.8
[[100  25]
 [ 17  68]]
auc: 0.8832


In [86]:
    X_tmp, y_tmp, X_test, y_test = iterative_train_test_split(
        np.array(feature_matrix),
        np.array(target[["food"]]),
        test_size=0.2,
        random_state=10191994)

    X_train, y_train, X_validation, y_validation = iterative_train_test_split(
        X_tmp,
        y_tmp,
        test_size=0.25, # 0.25 * 0.8 = 0.2
        random_state=10191994)

In [91]:
with open("../../0_data/5_train_validation_test/X_train.pickle", "wb") as f:
    pickle.dump(X_train, f)

In [92]:
X_train_test = pickle.load(open("../../0_data/5_train_validation_test/X_train.pickle", "rb"))

In [93]:
X_train == X_train_test

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

#### New models with 1000 iterations sped up

In [119]:
ambiance = pickle.load(open("../../4_models/rf_ambiance_5iterations_athreshold_5000_200.pickle", "rb"))
price = pickle.load(open("../../4_models/rf_price_5iterations_athreshold_5000_200.pickle", "rb"))
# service = pickle.load(open("../../4_models/rf_service_5iterations_athreshold_5000_200.pickle", "rb"))
# food = pickle.load(open("../../4_models/rf_food_5iterations_athreshold_5000_200.pickle", "rb"))

ambiance_i = pickle.load(open("../../4_models/rf_ambiance_5iterations_athreshold_5000_200initial.pickle", "rb"))
price_i = pickle.load(open("../../4_models/rf_price_5iterations_athreshold_5000_200initial.pickle", "rb"))
# service_i = pickle.load(open("../../4_models/rf_service_5iterations_athreshold_5000_200initial.pickle", "rb"))
# food_i = pickle.load(open("../../4_models/rf_food_5iterations_athreshold_5000_200initial.pickle", "rb"))

In [97]:
X_train_ambiance = pickle.load(open("../../0_data/5_train_validation_test/X_train_ambiance_1050.pickle", "rb"))
y_train_ambiance = pickle.load(open("../../0_data/5_train_validation_test/X_train_ambiance_1050.pickle", "rb"))
X_validation_ambiance = pickle.load(open("../../0_data/5_train_validation_test/X_validation_ambiance_1050.pickle", "rb"))
y_validation_ambiance = pickle.load(open("../../0_data/5_train_validation_test/y_validation_ambiance_1050.pickle", "rb"))
X_test_ambiance = pickle.load(open("../../0_data/5_train_validation_test/X_test_ambiance_1050.pickle", "rb"))
y_test_ambiance = pickle.load(open("../../0_data/5_train_validation_test/y_test_ambiance_1050.pickle", "rb"))

In [105]:
print(ambiance_i.score(X_validation_ambiance[:,1:], y_validation_ambiance))
print(ambiance_i.score(X_test_ambiance[:,1:], y_test_ambiance))

0.7904761904761904
0.7857142857142857


In [106]:
print(ambiance.score(X_validation_ambiance[:,1:], y_validation_ambiance))
print(ambiance.score(X_test_ambiance[:,1:], y_test_ambiance))

0.8047619047619048
0.7857142857142857


In [110]:
def test2(clf, clf2, features, target):
    
    print(clf.score(features[:, 1:], target))
    print(confusion_matrix(target,
            clf.predict(features[:, 1:])))
    fpr, tpr, _ = roc_curve(target,
                    clf.predict_proba(features[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)
    
    print(clf2.score(features[:, 1:], target))
    print(confusion_matrix(target,
            clf2.predict(features[:, 1:])))
    fpr, tpr, _ = roc_curve(target,
                    clf2.predict_proba(features[:, 1:])[:,1])
    auc_score = auc(fpr, tpr)
    print("auc:", auc_score)

In [111]:
test2(ambiance_i, ambiance, X_validation_ambiance, y_validation_ambiance)

0.7904761904761904
[[102  23]
 [ 21  64]]
auc: 0.8817882352941177
0.8047619047619048
[[102  23]
 [ 18  67]]
auc: 0.8844235294117646


In [112]:
test2(ambiance_i, ambiance, X_test_ambiance, y_test_ambiance)

0.7857142857142857
[[101  24]
 [ 21  64]]
auc: 0.8815058823529411
0.7857142857142857
[[102  23]
 [ 22  63]]
auc: 0.8742588235294118


In [117]:
sorted(list(zip(feature_names, ambiance_i.feature_importances_)), key=lambda x: -x[1])

[('ambiance_3avg_similarity', 0.4558579486446677),
 ('patio_3avg_similarity', 0.2538761719992587),
 ('loud_3avg_similarity', 0.13852747194738405),
 ('topic_0', 0.02701418452551707),
 ('topic_8', 0.007329089163042121),
 ('topic_25', 0.007008817937162035),
 ('say', 0.0066878442119556),
 ('staff_3avg_sim', 0.006197194821548695),
 ('topic_30', 0.005869708140676059),
 ('service_3avg_sim', 0.00339727042399861),
 ('topic_22', 0.003247900260025838),
 ('topic_13', 0.0032361751689151375),
 ('topic_94', 0.0029957788771828925),
 ('topic_70', 0.0027088922008283766),
 ('food_3avg_sim', 0.0020995114527998936),
 ('ask', 0.0020636811294479245),
 ('NOUN_VERB', 0.0019543215329108476),
 ('topic_6', 0.001813823492936451),
 ('topic_84', 0.0015538830896689789),
 ('topic_68', 0.0014710507612989286),
 ('VERB', 0.0013889827190943956),
 ('topic_33', 0.00134796086013714),
 ('topic_85', 0.0012694350887545044),
 ('ADJ_VERB', 0.0012681018365810603),
 ('topic_48', 0.001258964580345355),
 ('topic_62', 0.00123686561935

In [118]:
sorted(list(zip(feature_names, ambiance.feature_importances_)), key=lambda x: -x[1])

[('ambiance_3avg_similarity', 0.35839331633289556),
 ('patio_3avg_similarity', 0.24405065511934398),
 ('loud_3avg_similarity', 0.11346520866491103),
 ('NUM_PRT', 0.02679186607357159),
 ('topic_0', 0.023692314930308992),
 ('PRT_ADP', 0.02008109591272813),
 ('ADP_PRT', 0.018049777226566394),
 ('ADP_PRON', 0.015993480607932275),
 ('X_ADV', 0.015585555339774708),
 ('DET_NUM', 0.010949355650136067),
 ('VERB_X', 0.010392233073788814),
 ('DET_ADJ', 0.006882368203090748),
 ('ADJ_PRON', 0.005607815341742539),
 ('X_NUM', 0.003842455502822009),
 ('VERB_CONJ', 0.003481095262763138),
 ('topic_94', 0.003374257173869914),
 ('._ADJ', 0.0033698763126266103),
 ('topic_22', 0.0032892265339673366),
 ('PRON_ADP', 0.0031581693199852806),
 ('CONJ_.', 0.002864871098862958),
 ('X', 0.002820003882254138),
 ('._X', 0.0027913603253464435),
 ('ADJ_.', 0.002596632987635927),
 ('._DET', 0.0024736184627868777),
 ('say', 0.0022168111990189952),
 ('wait', 0.0021719132395402155),
 ('topic_25', 0.0021691006261968754),
 (

In [120]:
X_train_price = pickle.load(open("../../0_data/5_train_validation_test/X_train_price_1050.pickle", "rb"))
y_train_price = pickle.load(open("../../0_data/5_train_validation_test/X_train_price_1050.pickle", "rb"))
X_validation_price = pickle.load(open("../../0_data/5_train_validation_test/X_validation_price_1050.pickle", "rb"))
y_validation_price = pickle.load(open("../../0_data/5_train_validation_test/y_validation_price_1050.pickle", "rb"))
X_test_price = pickle.load(open("../../0_data/5_train_validation_test/X_test_price_1050.pickle", "rb"))
y_test_price = pickle.load(open("../../0_data/5_train_validation_test/y_test_price_1050.pickle", "rb"))

In [121]:
print(price_i.score(X_validation_price[:,1:], y_validation_price))
print(price_i.score(X_test_price[:,1:], y_test_price))
print(price.score(X_validation_price[:,1:], y_validation_price))
print(price.score(X_test_price[:,1:], y_test_price))

0.8428571428571429
0.8523809523809524
0.8476190476190476
0.8333333333333334


In [122]:
test2(price_i, price, X_validation_price, y_validation_price)
test2(price_i, price, X_test_price, y_test_price)

0.8428571428571429
[[129  26]
 [  7  48]]
auc: 0.9006451612903226
0.8476190476190476
[[130  25]
 [  7  48]]
auc: 0.8966568914956011
0.8523809523809524
[[130  25]
 [  6  49]]
auc: 0.9364222873900294
0.8333333333333334
[[125  30]
 [  5  50]]
auc: 0.9334897360703812


In [123]:
sorted(list(zip(feature_names, price_i.feature_importances_)), key=lambda x: -x[1])

[('price_3avg_similarity', 0.48843606479083196),
 ('cost_3avg_similarity', 0.183442724447168),
 ('price', 0.08757063113538309),
 ('sen_money_len', 0.04890524594984686),
 ('sen_num_len', 0.012631665240473908),
 ('topic_94', 0.011848362483043346),
 ('topic_12', 0.011010819566002401),
 ('topic_13', 0.009403895702347719),
 ('seat', 0.006823037850640526),
 ('topic_72', 0.005498916183667596),
 ('topic_39', 0.004843725256622374),
 ('topic_91', 0.004339339844485779),
 ('topic_55', 0.004251314890907921),
 ('topic_64', 0.004006993937026861),
 ('topic_86', 0.0037427991664611858),
 ('order', 0.003730039570397116),
 ('topic_28', 0.0036870791572725255),
 ('topic_71', 0.003361006853171883),
 ('topic_70', 0.0030765000101175425),
 ('topic_8', 0.0028624229278661397),
 ('NUM', 0.002693936510123034),
 ('food_3avg_sim', 0.002658458947160919),
 ('topic_63', 0.0024479550128475996),
 ('topic_18', 0.002373288264280399),
 ('topic_60', 0.001999992014206205),
 ('delici', 0.0019501688277381321),
 ('recommend', 0.0

In [124]:
sorted(list(zip(feature_names, price.feature_importances_)), key=lambda x: -x[1])

[('price_3avg_similarity', 0.43822485215508555),
 ('cost_3avg_similarity', 0.17646642774982266),
 ('price', 0.06179513541172375),
 ('sen_money_len', 0.03696024001911172),
 ('NUM_PRT', 0.019312189610868526),
 ('PRON_NUM', 0.01877654610640818),
 ('CONJ_NOUN', 0.013911134951088795),
 ('VERB_X', 0.01265852668713156),
 ('NUM_ADV', 0.010340601012354641),
 ('sen_num_len', 0.008505689464085418),
 ('X', 0.008327363105890566),
 ('seat', 0.008086905322219099),
 ('topic_12', 0.007722727728945856),
 ('ADV_DET', 0.006499453701213759),
 ('topic_94', 0.005155683148657939),
 ('._X', 0.004855973703262286),
 ('topic_91', 0.004062843410752775),
 ('._DET', 0.003882743061294749),
 ('topic_64', 0.003859779469666177),
 ('order', 0.0037629779285904687),
 ('topic_86', 0.003611342336797247),
 ('topic_13', 0.003420383810840834),
 ('VERB_CONJ', 0.00325367592576934),
 ('service_3avg_sim', 0.0031184558743326467),
 ('ADJ_PRON', 0.0030322202461027176),
 ('NOUN_PRON', 0.002928687825470511),
 ('topic_72', 0.002915857288

In [126]:
pred_proba = price.predict_proba(X_validation[:,1:])